; PlatformIO Project Configuration File
; ESP32-S3-WROOM-1 N16R8 (16MB Flash / 8MB PSRAM OPI)

[env:esp32-s3-devkitc-1]
platform = espressif32 @ 6.8.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; --- Konfiguracja sprzętowa N16R8 ---
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = partitions_16MB_littlefs.csv

; --- Flagi kompilacji ---
build_unflags = 
    -std=gnu++11

build_flags = 
    -std=gnu++17
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=3
    -O2
    -DCONFIG_ARDUINO_ISR_IRAM
    -DCONFIG_LWIP_TCP_WND_DEFAULT=32768

; --- Biblioteki ---
lib_deps = 
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    bblanchon/ArduinoJson @ ^7.0.0
    moononournation/GFX Library for Arduino@1.4.7
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.12hg
    LittleFS